# Markdown template
MARKDOWN_TEMPLATE = """\
# Business Requirement Breakdown

**Original Requirement:**
{original_requirement}

---

## Needs Identified:
{needs_section}

---
*Generated by ADK Agent on {timestamp}*
"""

MARKDOWN_NEED_SECTION_TEMPLATE = """\

### Need: {need_name}
*   **Description:** {need_description}
*   **Impact of Not Doing:** {need_impact}
{epic_section}
"""

MARKDOWN_EPIC_SECTION_TEMPLATE = """\

#### Epic for Need: {need_name}
*   **Title:** {epic_title}
*   **Description:** {epic_description}
{stories_section}
"""

MARKDOWN_STORIES_SECTION_TEMPLATE = """\

##### Stories for Epic: {epic_title}
{stories_list}
"""

MARKDOWN_STORY_TEMPLATE = """\
*   Story: {story_title}
    *   Description: {story_description}
"""
